# Generated by Django 2.0.3 on 2018-03-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barn_hunt', '0002_auto_20180325_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='trial_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barn_hunt.TrialClass'),
        ),
    ]
